install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - gem install bundler -v 1.12.5
  - bundle _1.12.5_ install  

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle _1.12.5_ exec rake spec
